version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ADDON_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_ADDON_DB}
      - MYSQL_USER=${MYSQL_ADDON_USER}
      - MYSQL_PASSWORD=${MYSQL_ADDON_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - springboot-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  springboot-app:
    image: cv24v1-app
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-app
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://${MYSQL_ADDON_HOST}:${MYSQL_ADDON_PORT}/${MYSQL_ADDON_DB}
      - SPRING_DATASOURCE_USERNAME=${MYSQL_ADDON_USER}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_ADDON_PASSWORD}
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - springboot-network

networks:
  springboot-network:
    driver: bridge
