//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.10 at 12:01:46 PM UTC 
//


package fr.univrouen.cv24v1.model;

import jakarta.xml.bind.annotation.*;


/**
 * <p>Java class for cv complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="cv"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element ref="{http://univrouen.fr/cv24v1/model}identite"/&gt;
 *         &lt;element ref="{http://univrouen.fr/cv24v1/model}objectif"/&gt;
 *         &lt;element ref="{http://univrouen.fr/cv24v1/model}prof" minOccurs="0"/&gt;
 *         &lt;element ref="{http://univrouen.fr/cv24v1/model}competences"/&gt;
 *         &lt;element ref="{http://univrouen.fr/cv24v1/model}divers" minOccurs="0"/&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "cv", propOrder = {

})
@XmlSeeAlso({
        Identite.class,
        Genre.class,
        Cert.class,
        Certif.class,
        Competences.class,
        Detail.class,
        Diplome.class,
        Divers.class,
        Lv.class,
        Nivs.class,
        Objectif.class,
        Prof.class,
        Statut.class,
        Autre.class
})
@XmlRootElement(name = "cv24", namespace = "http://univrouen.fr/cv24v1/model")
public class Cv {

    @XmlElement(required = true)
    protected Identite identite;
    @XmlElement(required = true)
    protected Objectif objectif;
    protected Prof prof;
    @XmlElement(required = true)
    protected Competences competences;
    protected Divers divers;

    /**
     * Gets the value of the identite property.
     * 
     * @return
     *     possible object is
     *     {@link Identite }
     *     
     */
    public Identite getIdentite() {
        return identite;
    }

    /**
     * Sets the value of the identite property.
     * 
     * @param value
     *     allowed object is
     *     {@link Identite }
     *     
     */
    public void setIdentite(Identite value) {
        this.identite = value;
    }

    /**
     * Gets the value of the objectif property.
     * 
     * @return
     *     possible object is
     *     {@link Objectif }
     *     
     */
    public Objectif getObjectif() {
        return objectif;
    }

    /**
     * Sets the value of the objectif property.
     * 
     * @param value
     *     allowed object is
     *     {@link Objectif }
     *     
     */
    public void setObjectif(Objectif value) {
        this.objectif = value;
    }

    /**
     * Gets the value of the prof property.
     * 
     * @return
     *     possible object is
     *     {@link Prof }
     *     
     */
    public Prof getProf() {
        return prof;
    }

    /**
     * Sets the value of the prof property.
     * 
     * @param value
     *     allowed object is
     *     {@link Prof }
     *     
     */
    public void setProf(Prof value) {
        this.prof = value;
    }

    /**
     * Gets the value of the competences property.
     * 
     * @return
     *     possible object is
     *     {@link Competences }
     *     
     */
    public Competences getCompetences() {
        return competences;
    }

    /**
     * Sets the value of the competences property.
     * 
     * @param value
     *     allowed object is
     *     {@link Competences }
     *     
     */
    public void setCompetences(Competences value) {
        this.competences = value;
    }

    /**
     * Gets the value of the divers property.
     * 
     * @return
     *     possible object is
     *     {@link Divers }
     *     
     */
    public Divers getDivers() {
        return divers;
    }

    /**
     * Sets the value of the divers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Divers }
     *     
     */
    public void setDivers(Divers value) {
        this.divers = value;
    }

}
