//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.10 at 12:01:46 PM UTC 
//


package fr.univrouen.cv24v1.model;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for lv complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="lv"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="lang" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="cert" use="required" type="{http://univrouen.fr/cv24v1/model}cert" /&gt;
 *       &lt;attribute name="nivs" type="{http://univrouen.fr/cv24v1/model}nivs" /&gt;
 *       &lt;attribute name="nivi" type="{http://univrouen.fr/cv24v1/model}nivi" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "lv")
public class Lv {

    @XmlAttribute(name = "lang", required = true)
    protected String lang;
    @XmlAttribute(name = "cert", required = true)
    protected Cert cert;
    @XmlAttribute(name = "nivs")
    protected Nivs nivs;
    @XmlAttribute(name = "nivi")
    protected Integer nivi;

    /**
     * Gets the value of the lang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLang() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLang(String value) {
        this.lang = value;
    }

    /**
     * Gets the value of the cert property.
     * 
     * @return
     *     possible object is
     *     {@link Cert }
     *     
     */
    public Cert getCert() {
        return cert;
    }

    /**
     * Sets the value of the cert property.
     * 
     * @param value
     *     allowed object is
     *     {@link Cert }
     *     
     */
    public void setCert(Cert value) {
        this.cert = value;
    }

    /**
     * Gets the value of the nivs property.
     * 
     * @return
     *     possible object is
     *     {@link Nivs }
     *     
     */
    public Nivs getNivs() {
        return nivs;
    }

    /**
     * Sets the value of the nivs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Nivs }
     *     
     */
    public void setNivs(Nivs value) {
        this.nivs = value;
    }

    /**
     * Gets the value of the nivi property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNivi() {
        return nivi;
    }

    /**
     * Sets the value of the nivi property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNivi(Integer value) {
        this.nivi = value;
    }

}
