//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.10 at 12:01:46 PM UTC 
//


package fr.univrouen.cv24v1.model;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the fr.univrouen.cv24v1.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Cv24_QNAME = new QName("http://univrouen.fr/cv24v1/model", "cv24v1");
    private final static QName _Identite_QNAME = new QName("http://univrouen.fr/cv24v1/model", "identite");
    private final static QName _Genre_QNAME = new QName("http://univrouen.fr/cv24v1/model", "genre");
    private final static QName _Nom_QNAME = new QName("http://univrouen.fr/cv24v1/model", "nom");
    private final static QName _Prenom_QNAME = new QName("http://univrouen.fr/cv24v1/model", "prenom");
    private final static QName _Tel_QNAME = new QName("http://univrouen.fr/cv24v1/model", "tel");
    private final static QName _Mel_QNAME = new QName("http://univrouen.fr/cv24v1/model", "mel");
    private final static QName _Objectif_QNAME = new QName("http://univrouen.fr/cv24v1/model", "objectif");
    private final static QName _Detail_QNAME = new QName("http://univrouen.fr/cv24v1/model", "detail");
    private final static QName _Datedeb_QNAME = new QName("http://univrouen.fr/cv24v1/model", "datedeb");
    private final static QName _Datefin_QNAME = new QName("http://univrouen.fr/cv24v1/model", "datefin");
    private final static QName _Titre_QNAME = new QName("http://univrouen.fr/cv24v1/model", "titre");
    private final static QName _Prof_QNAME = new QName("http://univrouen.fr/cv24v1/model", "prof");
    private final static QName _Competences_QNAME = new QName("http://univrouen.fr/cv24v1/model", "competences");
    private final static QName _Diplome_QNAME = new QName("http://univrouen.fr/cv24v1/model", "diplome");
    private final static QName _Date_QNAME = new QName("http://univrouen.fr/cv24v1/model", "date");
    private final static QName _Institut_QNAME = new QName("http://univrouen.fr/cv24v1/model", "institut");
    private final static QName _Certif_QNAME = new QName("http://univrouen.fr/cv24v1/model", "certif");
    private final static QName _Divers_QNAME = new QName("http://univrouen.fr/cv24v1/model", "divers");
    private final static QName _Lv_QNAME = new QName("http://univrouen.fr/cv24v1/model", "lv");
    private final static QName _Autre_QNAME = new QName("http://univrouen.fr/cv24v1/model", "autre");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: fr.univrouen.cv24v1.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Cv }
     * 
     */
    public Cv createCv() {
        return new Cv();
    }

    /**
     * Create an instance of {@link Identite }
     * 
     */
    public Identite createIdentite() {
        return new Identite();
    }

    /**
     * Create an instance of {@link Objectif }
     * 
     */
    public Objectif createObjectif() {
        return new Objectif();
    }

    /**
     * Create an instance of {@link Detail }
     * 
     */
    public Detail createDetail() {
        return new Detail();
    }

    /**
     * Create an instance of {@link Prof }
     * 
     */
    public Prof createProf() {
        return new Prof();
    }

    /**
     * Create an instance of {@link Competences }
     * 
     */
    public Competences createCompetences() {
        return new Competences();
    }

    /**
     * Create an instance of {@link Diplome }
     * 
     */
    public Diplome createDiplome() {
        return new Diplome();
    }

    /**
     * Create an instance of {@link Certif }
     * 
     */
    public Certif createCertif() {
        return new Certif();
    }

    /**
     * Create an instance of {@link Divers }
     * 
     */
    public Divers createDivers() {
        return new Divers();
    }

    /**
     * Create an instance of {@link Lv }
     * 
     */
    public Lv createLv() {
        return new Lv();
    }

    /**
     * Create an instance of {@link Autre }
     * 
     */
    public Autre createAutre() {
        return new Autre();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Cv }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Cv }{@code >}
     */
    @XmlElementDecl(namespace = "http://univrouen.fr/cv24v1/model", name = "cv24v1")
    public JAXBElement<Cv> createCv24(Cv value) {
        return new JAXBElement<Cv>(_Cv24_QNAME, Cv.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Identite }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Identite }{@code >}
     */
    @XmlElementDecl(namespace = "http://univrouen.fr/cv24v1/model", name = "identite")
    public JAXBElement<Identite> createIdentite(Identite value) {
        return new JAXBElement<Identite>(_Identite_QNAME, Identite.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Genre }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Genre }{@code >}
     */
    @XmlElementDecl(namespace = "http://univrouen.fr/cv24v1/model", name = "genre")
    public JAXBElement<Genre> createGenre(Genre value) {
        return new JAXBElement<Genre>(_Genre_QNAME, Genre.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://univrouen.fr/cv24v1/model", name = "nom")
    public JAXBElement<String> createNom(String value) {
        return new JAXBElement<String>(_Nom_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://univrouen.fr/cv24v1/model", name = "prenom")
    public JAXBElement<String> createPrenom(String value) {
        return new JAXBElement<String>(_Prenom_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://univrouen.fr/cv24v1/model", name = "tel")
    public JAXBElement<String> createTel(String value) {
        return new JAXBElement<String>(_Tel_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://univrouen.fr/cv24v1/model", name = "mel")
    public JAXBElement<String> createMel(String value) {
        return new JAXBElement<String>(_Mel_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Objectif }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Objectif }{@code >}
     */
    @XmlElementDecl(namespace = "http://univrouen.fr/cv24v1/model", name = "objectif")
    public JAXBElement<Objectif> createObjectif(Objectif value) {
        return new JAXBElement<Objectif>(_Objectif_QNAME, Objectif.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Detail }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Detail }{@code >}
     */
    @XmlElementDecl(namespace = "http://univrouen.fr/cv24v1/model", name = "detail")
    public JAXBElement<Detail> createDetail(Detail value) {
        return new JAXBElement<Detail>(_Detail_QNAME, Detail.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://univrouen.fr/cv24v1/model", name = "datedeb")
    public JAXBElement<String> createDatedeb(String value) {
        return new JAXBElement<String>(_Datedeb_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://univrouen.fr/cv24v1/model", name = "datefin")
    public JAXBElement<String> createDatefin(String value) {
        return new JAXBElement<String>(_Datefin_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://univrouen.fr/cv24v1/model", name = "titre")
    public JAXBElement<String> createTitre(String value) {
        return new JAXBElement<String>(_Titre_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Prof }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Prof }{@code >}
     */
    @XmlElementDecl(namespace = "http://univrouen.fr/cv24v1/model", name = "prof")
    public JAXBElement<Prof> createProf(Prof value) {
        return new JAXBElement<Prof>(_Prof_QNAME, Prof.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Competences }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Competences }{@code >}
     */
    @XmlElementDecl(namespace = "http://univrouen.fr/cv24v1/model", name = "competences")
    public JAXBElement<Competences> createCompetences(Competences value) {
        return new JAXBElement<Competences>(_Competences_QNAME, Competences.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Diplome }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Diplome }{@code >}
     */
    @XmlElementDecl(namespace = "http://univrouen.fr/cv24v1/model", name = "diplome")
    public JAXBElement<Diplome> createDiplome(Diplome value) {
        return new JAXBElement<Diplome>(_Diplome_QNAME, Diplome.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://univrouen.fr/cv24v1/model", name = "date")
    public JAXBElement<String> createDate(String value) {
        return new JAXBElement<String>(_Date_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://univrouen.fr/cv24v1/model", name = "institut")
    public JAXBElement<String> createInstitut(String value) {
        return new JAXBElement<String>(_Institut_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Certif }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Certif }{@code >}
     */
    @XmlElementDecl(namespace = "http://univrouen.fr/cv24v1/model", name = "certif")
    public JAXBElement<Certif> createCertif(Certif value) {
        return new JAXBElement<Certif>(_Certif_QNAME, Certif.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Divers }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Divers }{@code >}
     */
    @XmlElementDecl(namespace = "http://univrouen.fr/cv24v1/model", name = "divers")
    public JAXBElement<Divers> createDivers(Divers value) {
        return new JAXBElement<Divers>(_Divers_QNAME, Divers.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Lv }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Lv }{@code >}
     */
    @XmlElementDecl(namespace = "http://univrouen.fr/cv24v1/model", name = "lv")
    public JAXBElement<Lv> createLv(Lv value) {
        return new JAXBElement<Lv>(_Lv_QNAME, Lv.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Autre }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Autre }{@code >}
     */
    @XmlElementDecl(namespace = "http://univrouen.fr/cv24v1/model", name = "autre")
    public JAXBElement<Autre> createAutre(Autre value) {
        return new JAXBElement<Autre>(_Autre_QNAME, Autre.class, null, value);
    }

}
