//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.10 at 12:01:46 PM UTC 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://univrouen.fr/cv24v1/model", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package fr.univrouen.cv24v1.model;
